### PR TITLE
include recent spellings of production units in AI data

### PR DESCRIPTION
**Pull request by cjyetman**
Recent versions of AI data include new spellings of production units.

``` r
library(tidyverse)
pams_path <- "~/data/pactarawdata/asset-impact/2024-02-15_AI_RMI_2023Q4/2024-02-14_AI_2023Q4_RMI-Company-Indicators.xlsx"
pams <- pacta.data.preparation::import_ar_advanced_company_indicators(pams_path)
pams %>% filter(value_type == "production") %>% select(`Asset Sector`, `Activity Unit`) %>% distinct() %>% arrange(`Asset Sector`, `Activity Unit`)
#> # A tibble: 11 × 2
#>    `Asset Sector` `Activity Unit`
#>    <fct>          <fct>          
#>  1 Aviation       pkm            
#>  2 Aviation       tkm            
#>  3 Cement         t cement       
#>  4 Coal           t coal         
#>  5 HDV            # vehicles     
#>  6 LDV            # vehicles     
#>  7 Oil&Gas        GJ             
#>  8 Power          MW             
#>  9 Power          MWh            
#> 10 Shipping       dwt km         
#> 11 Steel          t steel
```

### CODE REVIEW

**Review by jdhoffa — APPROVED** [review]
lgtm

NB: does/ will/ should this affect anything downstream? 
NB: do we need to adjust production units in scenarios?

**Comment by cjyetman** [comment]
> NB: does/ will/ should this affect anything downstream?

from what I've seen/realized so far, this does not impact anything other than allowing the data validation functions to pass, which are not implemented in production anywhere (yet)

> NB: do we need to adjust production units in scenarios?

this might suggest that, but I honestly don't know yet... if so, it probably implies that we need a `standardize_units()` type function in pacta.data.preparation that would standardize units from our various source data (AI, scenarios, ISS?) to some PACTA standard unit names

**Comment by jacobvjk** [comment]
does it imply changes in PAMS only or also in the banks data set? I am using the activity units based on `r2dii.data::abcd_demo[["production_unit"]]` in P4S

**Comment by cjyetman** [comment]
> does it imply changes in PAMS only or also in the banks data set? I am using the activity units based on `r2dii.data::abcd_demo[["production_unit"]]` in P4S

I have too little experience with Banks data to know. I'm tempted to say "yes", since I somewhat doubt they would bother to modify custom units specifically for the Banks data, but I really have no context. These new units are in the PAMS dataset that we received in Feb for 23Q4, and I assume we also received a set of Banks data at the same time (?), so should be easy to check.

**Pull request merged**
